export const data = [
  {
    name: "Jan",
    "Active User": 4000,
  },
  {
    name: "Feb",
    "Active User": 3000,
  },
  {
    name: "March",
    "Active User": 4200,
  },
  {
    name: "Apr",
    "Active User": 5000,
  },
  {
    name: "May",
    "Active User": 4800,
  },
  {
    name: "Jun",
    "Active User": 3500,
  },
  {
    name: "Jul",
    "Active User": 3000,
  },
  {
    name: "Aug",
    "Active User": 3600,
  },
  {
    name: "Sep",
    "Active User": 4000,
  },
  {
    name: "Oct",
    "Active User": 3800,
  },
  {
    name: "Nov",
    "Active User": 3500,
  },
  {
    name: "Dec",
    "Active User": 5500,
  },
];

export const productData = [
  {
    name: "Jan",
    sales: 4000,
  },
  {
    name: "Feb",
    sales: 3000,
  },
  {
    name: "March",
    sales: 4200,
  },
];

export const rows = [
  {
    id: 1,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
  {
    id: 2,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
  {
    id: 3,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
  {
    id: 4,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
  {
    id: 5,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
  {
    id: 6,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
  {
    id: 7,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
  {
    id: 8,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
  {
    id: 8,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
  {
    id: 8,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
  {
    id: 8,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
  {
    id: 8,
    username: "jon",
    avatar: "https://www.bollywoodfever.co.in/wp-content/uploads/2021/05/abigail-shapiro-Hot-.jpg",
    email: "jon@gmail.com",
    status: "active",
    transactions: "120",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
  {
    id: 2,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
  {
    id: 3,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
  {
    id: 4,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
  {
    id: 5,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
  {
    id: 6,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
  {
    id: 7,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
  {
    id: 8,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
  {
    id: 9,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
  {
    id: 10,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
  {
    id: 11,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
  {
    id: 12,
    name: "Apple Ipods",
    img: "https://www.petunjuk.co.id/thumbs/products/l/6732-apple-ipod-classic.jpg",
    stock: 12,
    status: "active",
    price: "120",
  },
];
