import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Sidebar from "../components/Sidebar";
import Topbar from "../components/Topbar";
import HomeSection from "../sections/HomeSection";
import LoginSection from "../sections/LoginSection";
import NewProduct from "../sections/NewProduct";
import NewUser from "../sections/NewUser";
import ProductList from "../sections/ProductList";
import ProductSection from "../sections/ProductSection";
import UserSection from "../sections/UserSection";
import UsersSection from "../sections/UsersSection";

export default function Home() {
  const [admin, setAdmin] = useState(null);
  const router = useRouter();
  const { index } = router.query;
  const indexs = index || [];
  const exceptions = ["login", "register"];

  useEffect(() => {
    setAdmin(
      JSON.parse(JSON.parse(localStorage.getItem("persist:root")).user)
        .currentUser?.isAdmin || false
    );
  }, []);

  useEffect(() => {
    if (admin !== null) {
      if (!admin && !exceptions.includes(indexs[0])) {
        router.push("/login");
      }
      if (admin && exceptions.includes(indexs[0])) {
        router.push("/home");
      }
    }
  }, [admin]);

  return (
    <div className="home">
      <Head>
        <title>{indexs[0]}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {exceptions.includes(indexs[0]) && (
        <>{indexs[0] == "login" && <LoginSection />}</>
      )}

      {!exceptions.includes(indexs[0]) && admin && (
        <>
          <Topbar />
          <div className="sideMain">
            <Sidebar index={indexs[0]} />
            {indexs[0] == "home" && <HomeSection />}
            {indexs[0] == "users" && <UsersSection />}
            {indexs[0] == "user" && <UserSection id={indexs[1]} />}
            {indexs[0] == "newUser" && <NewUser />}
            {indexs[0] == "products" && <ProductList />}
            {indexs[0] == "product" && <ProductSection id={indexs[1]} />}
            {indexs[0] == "newProduct" && <NewProduct />}
          </div>
        </>
      )}
    </div>
  );
}
